import snowflake.connector

# Snowflake connection details
sf_account = 'ec84347.ap-southeast-3.aws'
sf_user = 'zulfakarjastine'
sf_password = 'Misterice99'
sf_warehouse = 'COMPUTE_WH'
sf_database = 'FINALPROJECT'
sf_schema = 'PUBLIC'

# Connect to Snowflake
conn = snowflake.connector.connect(
    account=sf_account,
    user=sf_user,
    password=sf_password,
    warehouse=sf_warehouse,
    database=sf_database,
    schema=sf_schema
)

# Create a cursor
cursor = conn.cursor()

# List of INSERT queries
insert_queries = [
    "CREATE TABLE Jastine_DailyGrosRev AS SELECT ORDER_DATE, SUM(GROSS_REVENUE) TOTAL_GROSS_REVENUE FROM (SELECT (1-B.DISCOUNT)*B.UNIT_PRICE*B.QUANTITY GROSS_REVENUE, A.ORDER_DATE FROM ORDERS A LEFT JOIN ORDER_DETAILS B ON A.ORDER_ID = B.ORDER_ID) GROUP BY ORDER_DATE ORDER BY ORDER_DATE;",
    "CREATE TABLE Jastine_MonthlyGrossRevPerProduct AS SELECT ORDER_MONTH, PRODUCT_NAME, SUM(GROSS_REVENUE) TOTAL_GROSS_REVENUE FROM (SELECT (1-B.DISCOUNT)*B.UNIT_PRICE*B.QUANTITY GROSS_REVENUE, SUBSTR(ORDER_DATE,1,7) ORDER_MONTH, C.PRODUCT_NAME FROM ORDERS A LEFT JOIN ORDER_DETAILS B ON A.ORDER_ID = B.ORDER_ID LEFT JOIN PRODUCTS C ON B.PRODUCT_ID = C.PRODUCT_ID) GROUP BY ORDER_MONTH, PRODUCT_NAME ORDER BY ORDER_MONTH;", 
    "CREATE TABLE Jastine_MonthlyTotalPerProduct AS SELECT SUBSTR(A.ORDER_DATE,1,7) ORDER_MONTH, C.PRODUCT_NAME, COUNT(A.ORDER_ID) TOTAL_ORDER FROM ORDERS A LEFT JOIN ORDER_DETAILS B ON A.ORDER_ID = B.ORDER_ID LEFT JOIN PRODUCTS C ON B.PRODUCT_ID = C.PRODUCT_ID GROUP BY SUBSTR(A.ORDER_DATE,1,7), PRODUCT_NAME ORDER BY COUNT(A.ORDER_ID) DESC;",
    "CREATE TABLE Jastine_MonthlyTotalPerCat AS SELECT SUBSTR(A.ORDER_DATE,1,7) ORDER_MONTH, D.CATEGORY_NAME, COUNT(A.ORDER_ID) TOTAL_ORDER FROM ORDERS A LEFT JOIN ORDER_DETAILS B ON A.ORDER_ID = B.ORDER_ID LEFT JOIN PRODUCTS C ON B.PRODUCT_ID = C.PRODUCT_ID LEFT JOIN CATEGORIES D ON C.CATEGORY_ID = D.CATEGORY_ID GROUP BY SUBSTR(A.ORDER_DATE,1,7), D.CATEGORY_NAME ORDER BY COUNT(A.ORDER_ID) DESC;",
    "CREATE TABLE Jastine_MonthlyTotalPerCountry AS SELECT SUBSTR(A.ORDER_DATE,1,7) ORDER_MONTH, A.SHIP_COUNTRY, COUNT(A.ORDER_ID) TOTAL_ORDER FROM ORDERS A GROUP BY SUBSTR(A.ORDER_DATE,1,7), A.SHIP_COUNTRY;"
]

# Execute each INSERT query
for query in insert_queries:
    cursor.execute(query)

# Commit the changes
conn.commit()

# Close the cursor and connection
cursor.close()
conn.close()